CREATE DATABASE IF NOT EXISTS Burgers_db;
USE Burgers_db;


DROP TABLE IF EXISTS burgers;


CREATE TABLE burgers (
id INT(11) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(255) NOT NULL,
devoured BOOL DEFAULT false,
`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

